---
- hosts: all
  #serial: 1
  #strategy: free # improve parallelism but pause module doesn't works with it.
  #accelerate: true
  vars:
    burp_module_test_client: true
    burp_module_agent: true
  roles:
    - role: ansible_burp2_server
