# burp2_server

- src: coffeeitworks.burp2_server
  version: 1.34.1  # see https://github.com/CoffeeITWorks/ansible_burp2_server/releases
  # To use burp 2.3.x you can use:
  # src: https://github.com/CoffeeITWorks/ansible_burp2_server.git
  # version: burp-2.3.x 
  #
  # Ans see changelog of this branch for other breaking changes

- src: coffeeitworks.ansible_burpui_agent
  version: 1.1.1 # https://galaxy.ansible.com/coffeeitworks/ansible_burpui_agent

- src: coffeeitworks.burpui_server
  version: 1.8.0 # https://galaxy.ansible.com/coffeeitworks/burpui_server

- src: coffeeitworks.burp_reports
  version: v1.5.2 # https://galaxy.ansible.com/coffeeitworks/burp_reports

# Clients only
- src: coffeeitworks.burp2_client
  version: 1.6.0 # https://galaxy.ansible.com/coffeeitworks/burp2_client
