---
# file tasks/manual_delete.yml

- name: manual_delete | install cron packages
  package:
    name: "{{ cron_packages | join(',') }}"
    state: present

- name: ensure /etc/cron.d exists
  file:
    path: /etc/cron.d
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: '0755'

- name: manual_delete | create burp folders
  file:
    path: "{{ burp_trash }}"
    state: directory
    owner: "{{ burp_sv_server_user }}"
    group: "{{ burp_sv_server_user }}"
    mode: '0755'

- name: manual_delete | Cron task to delete files in burp trash
  cron:
    name: delete files in burp trash
    job: 'rm -rfv {{ burp_trash  }}/* >> {{ burp_logs }}/manual_delete.log'
    user: root
    cron_file: manual_delete
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.dow }}"
    state: present
  with_items: "{{ burp_cron_delete }}"
  notify: restart cron server

- name: manual_delete | configure burp logrotate
  template:
    src: burp_logrotate.j2
    dest: /etc/logrotate.d/burp

- name: manual_delete | Enable crond service
  service:
    name: "{{ cron_service }}"
    state: started
    enabled: yes
