---
# file tasks/autoupgrade.yml

- name: create autoupgrade clients dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ burp_server_autoupgrade_dir }}/win32/1.4.40"
    - "{{ burp_server_autoupgrade_dir }}/win64/1.4.40"

# documentation from:
# http://burp.grke.org/docs/autoupgrade.html

- name: copy burp client exe files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "autoupgrade_script", dest: "{{ burp_server_autoupgrade_dir }}/win32/script" }
    - { src: "autoupgrade_script", dest: "{{ burp_server_autoupgrade_dir }}/win64/script" }
    - { src: "burp-win32-installer-1.4.40.exe", dest: "{{ burp_server_autoupgrade_dir }}/win32/1.4.40/package" }
    - { src: "burp-win64-installer-1.4.40.exe", dest: "{{ burp_server_autoupgrade_dir }}/win64/1.4.40/package" }