- name: uninstall old burp package
  package:
    name: burp
    state: absent

- name: uninstall old burp package
  package:
    name: burp-server
    state: absent

- name: remove old burp server service
  file:
    path: /etc/init.d/burp-server
    state: absent

- name: remove old burp restore service
  file:
    path: /etc/init.d/burp-restore
    state: absent

- name: remove old default burp server service
  file:
    path: /etc/default/burp
    state: absent

- name: remove old default burp restore service
  file:
    path: /etc/default/burp-restore
    state: absent