---
# file: tasks/linux.yml

- name: Clone configuration directories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ burp_server_clientconfdir }}/{{ item.dir }}"
    version: "{{ item.version }}"
    update: yes
    force: yes
  with_items: "{{ burp_repos }}"

- name: Link client configuration files
  shell: "ln -fs {{ item.dir }}/* ./"
  args:
    chdir: "{{ burp_server_clientconfdir }}"
  with_items: "{{ burp_repos }}"
  changed_when: false

- name: Remove deprecated links
  shell: 'find . -type l -xtype l -exec rm -rf {} \;'
  args:
    chdir: "{{ burp_server_clientconfdir }}"
  changed_when: false