---
# file defaults/config_agent.yml

- name: install buiagent packages
  package:
    name: "{{ burp_agent_packages| join(',') }}"
    state: present

- name: install buiagent pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ burp_agent_pip_present }}"

- name: Install buiagent pip
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
  with_items: "{{ burpui_pip_packages }}"
  notify: restart buiagent


- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "/etc/burp/buiagent.cfg" }
  notify: restart buiagent

- name: ensure supervisor is restarted
  service:
    name: "{{ supervisor_service }}"
    state: restarted
    sleep: 5
    enabled: True
  changed_when: false
