---
# file tasks/config_restore.yml

- name: configure burp restore
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burp-restore.conf.j2", dest: "{{ etc_dir }}/burp/burp-restore.conf"}
  notify: restart burp restore