---
# file defaults/config_agent.yml

- name: install buiagent packages
  package:
    name: "{{ burp_agent_packages| join(',') }}"
    state: present
  when: ( ansible_os_family != "FreeBSD" or burp_use_portinstall == False )

- name: install buiagent packages
  portinstall:
    name: "{{ item }}"
    state: present
    use_packages: no
  with_items: "{{ burp_agent_packages}}"
  when: ( ansible_os_family == "FreeBSD" and burp_use_portinstall == True )

- name: install pip on FreeBSD with pythonic solution as ports are only pip2 ...
  command: python3.6 -m ensurepip
  args:
    creates: "{{python_pip_executable }}"
  when: ansible_os_family == "FreeBSD"

# workaround for ubuntu 14.04 with missing pip3 executable
- block:
    
    - name: stat to see if pip3 executable is present
      stat:
        path: '/usr/bin/pip3'
      register: pip3_executable_stat
    
    - name: Absent python3-pip if /usr/bin/pip3 is not present
      package:
        name: 'python3-pip'
        state: absent
      when: not pip3_executable_stat.stat.exists
  
  when: ansible_distribution_release == 'trusty'

- name: install buiagent packages for pip3
  package:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
  when: python_pip_executable == "pip3" and ( ansible_os_family != "FreeBSD" or burp_use_portinstall == False )

- name: install buiagent packages for pip3
  portinstall:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
    use_packages: no
  when: ( ansible_os_family == "FreeBSD" and burp_use_portinstall == True )  
  
- name: Uninstall buiagent pip2 packages when using pip3 as pip executable
  pip:
    name: "{{ burp_agent_pip_burpui }}"
    state: absent
    executable: "pip2"
  when: python_pip_executable == "pip3"
  # ports for py-pip are built for current python version
  when: ansible_os_family != "FreeBSD"
  
- name: install buiagent pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burp_agent_pip_present }}"

- name: Install buiagent pip
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burpui_pip_packages }}"
  notify: restart buiagent

- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "{{ etc_dir }}/burp/buiagent.cfg" }
  notify: restart buiagent

# On FreeBSD 11 there is no /var/log/supervisord directory by default
- name: supervisor | create /var/log/supervisord on FreeBSD
  file:
    path: "{{ burp_sv_server_log_dir }}"
    state: directory
  when: ansible_os_family == "FreeBSD"

- name: ensure supervisor is restarted
  service:
    name: "{{ supervisor_service }}"
    state: restarted
    sleep: 5
    enabled: True
  changed_when: false
