---
# file tasks/config_burp.yml

- name: create burp folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ burp_home }}"
    - "{{ burp_server_data }}"
    - "{{ burp_logs }}"
    - "{{ burp_server_clientconfdir }}/profiles"
    - "{{ burp_server_clientconfdir }}/incexc"

- name: remove burp example files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ burp_server_clientconfdir }}/testclient"
    - "{{ burp_server_clientconfdir }}/incexc/example"

- name: configure burp server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burp-server.conf.j2", dest: "{{ etc_dir }}/burp/burp-server.conf"}
  notify: restart burp server
  
- name: symlink ssl server certificates on FreeBSD
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "CA/CA_burpCA.crt", dest: "{{ etc_dir }}/burp/ssl_cert_ca-server.pem" }
    - { src: "CA/{{ ansible_hostname }}.key", dest: "{{ etc_dir }}/burp/ssl_cert-server.key" }
    - { src: "CA/{{ ansible_hostname }}.crt", dest: "{{ etc_dir }}/burp/ssl_cert-server.pem" }
  when: ansible_os_family == "FreeBSD"

- name: config_burp | configure profiles configured in profiles_templates
  template:
    src: profiles/profile_template.j2
    dest: "{{burp_server_clientconfdir}}/incexc/{{ item.name }}"
  with_items: "{{ profiles_templates }}"

- name: copy clients configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ burp_server_clientconfdir }}"
    directory_mode: yes
    force: yes
  with_items:
    - incexc

- name: configure profile lnxsrv to create new client
  template:
    src: profiles/lnxsrv.j2
    dest: "{{burp_server_clientconfdir}}/profiles/lnxsrv"

- name: configure profile win6x to create new client
  template:
    src: profiles/win6x.j2
    dest: "{{burp_server_clientconfdir}}/profiles/win6x"

# This task ensures we can create restore file for server initiated restores
- name: create restore client's dir in spool dir
  file:
    path: "{{ burp_server_data }}/{{ item }}"
    state: directory
  with_items: "{{ burp_restore_clients }}"
