---
# file defaults/config_agent.yml

- name: install buiagent packages
  package:
    name: "{{ burp_agent_packages| join(',') }}"
    state: present

# workaround for ubuntu 14.04 with missing pip3 executable
- block:
    
    - name: stat to see if pip3 executable is present
      stat:
        path: '/usr/bin/pip3'
      register: pip3_executable_stat
    
    - name: Absent python3-pip if /usr/bin/pip3 is not present
      package:
        name: 'python3-pip'
        state: absent
      when: not pip3_executable_stat.stat.exists

    - name: Uninstall python-six if present on trusty
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - python-six
        - python3-six
  
  when: ansible_distribution_release == 'trusty'

- name: stat to see if pip2 exists
  stat:
    path: '/usr/bin/pip2'
  register: pip2_executable_stat

- name: install buiagent packages for pip3
  package:
    name: "{{ burp_agent_py3_packages| join(',') }}"
    state: present
  when: python_pip_executable == "pip3"

- name: Uninstall buiagent pip2 packages when using pip3 as pip executable
  pip:
    name: "{{ burp_agent_pip_burpui }}"
    state: absent
    executable: "pip2"
  when: python_pip_executable == "pip3" and pip2_executable_stat.stat.exists

- name: install buiagent pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burp_agent_pip_present }}"

- name: Install buiagent pip
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "{{ python_pip_executable }}"
  with_items: "{{ burpui_pip_packages }}"
  notify: restart buiagent


- name: configure buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.cfg.j2", dest: "/etc/burp/buiagent.cfg" }
  notify: restart buiagent

- name: ensure supervisor is restarted
  service:
    name: "{{ supervisor_service }}"
    state: restarted
    sleep: 5
    enabled: True
  changed_when: false
