---
# file: tasks/main.yml

- include: 1_1_multi_os.yml

# - include: repositories.yml

# - include: install_burp.yml

# Include steps to be ready for unprivileged account
- include: 2_unprivileged_user.yml
  when: burp_sv_server_user != "root"

- include: 3_build-burp.yml

- include: 4_config_burp.yml

- include: 5_hotfix/burp_ca.yml
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10")

- include: 6_manual_client.yml

# Only for monitor and status purpose
- include: 7_1_manual_delete.yml
  when: burp_manual_delete_enabled

- include: 7_2_manual_delete_disabled.yml
  when: not burp_manual_delete_enabled

- include: 8_autoupgrade.yml
  when: burp_server_autoupgrade_enabled

- include: 9_clients_git.yml
  when: burp_repos
  tags: update_git_clients

- include: 10_local_client.yml

- include: deprecated/supervisor.yml
  when: burp_sv_type == 'supervisor'

- include: 11_systemd.yml
  when: burp_sv_type == 'systemd'

- name: wait for burpca to get all server certificates
  wait_for:
    path: "{{ item }}"
    state: present
  with_items:
    - '{{ burp_server_etc }}/ssl_cert_ca-server.pem'
    - '{{ burp_server_etc }}/ssl_cert-server.key'
    - '{{ burp_server_etc }}/ssl_cert-server.pem'

- name: flush handlers
  meta: flush_handlers

- include: 12_backup_tool_script.yml
  when: install_backup_tool_script

- include: 13_remove_client.yml
