---
# file: tasks/main.yml

- include: multi_os.yml

# - include: repositories.yml

# - include: install_burp.yml

# Include steps to be ready for unprivileged account
- include: unprivileged_user.yml
  when: burp_sv_server_user != "root"

- include: build-burp.yml

- include: config_burp.yml

- include: hotfix/burp_ca.yml
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10")

- include: manual_client.yml

# Only for monitor and status purpose
- include: manual_delete.yml
  when: burp_manual_delete_enabled

- include: manual_delete_disabled.yml
  when: not burp_manual_delete_enabled

- include: autoupgrade.yml
  when: burp_server_autoupgrade_enabled

- include: clients_git.yml
  when: burp_repos
  tags: update_git_clients

- include: local_client.yml

- include: supervisor.yml
  when: burp_sv_type == 'supervisor'

- include: systemd.yml
  when: burp_sv_type == 'systemd'

- name: wait for burpca to get all server certificates
  wait_for:
    path: "{{ item }}"
    state: present
  with_items:
    - '{{ burp_server_etc }}/ssl_cert_ca-server.pem'
    - '{{ burp_server_etc }}/ssl_cert-server.key'
    - '{{ burp_server_etc }}/ssl_cert-server.pem'

- name: flush handlers
  meta: flush_handlers

- include: backup_tool_script.yml
  when: install_backup_tool_script

- include: remove_client.yml
