---
# file: tasks/main.yml

- include: multi_os.yml

- include: redhat.yml
  when: ansible_os_family == "RedHat"

# - include: repositories.yml

# - include: install_burp.yml

# Clean any package distribution before start
- include: clean.yml

- include: build-burp.yml

- include: config_burp.yml

- include: manual_client.yml

# Only for monitor and status purpose
- include: manual_delete.yml
  when: burp_manual_delete_enabled

- include: manual_delete_disabled.yml
  when: not burp_manual_delete_enabled

- include: autoupgrade.yml
  when: burp_server_autoupgrade_enabled

- include: clients_git.yml
  when: burp_repos
  tags: update_git_clients

- include: config_restore.yml
  when: burp_module_restore

- include: local_client.yml

- include: config_agent.yml
  when: burp_module_agent

- include: supervisor.yml

- include: backup_tool_script.yml
  when: install_backup_tool_script

- include: tests/test_client.yml
  when: burp_module_test_client

- include: remove_client.yml
