---
# file tasks/manual_delete.yml

- name: install cron packages
  package:
    name: "{{ cron_packages | join(',') }}"
    state: present
  when: ( ansible_os_family != "FreeBSD" or burp_freebsd_use_portinstall == False )
  
- name: create burp folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ burp_trash }}"
    - "{{ burp_logs }}"
    - "{{ etc_dir }}/cron.d"

- name: Cron task to delete files in burp trash
  cron:
    name: delete files in burp trash
    job: 'rm -rfv {{ burp_trash  }}/* >> {{ burp_logs }}/manual_delete.log'
    user: root
    cron_file: manual_delete
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.dow }}"
    state: present
  with_items: "{{ burp_cron_delete }}"
  notify: restart cron server

- name: create logrotate.d folder
  file:
    path: "{{ etc_dir }}/logrotate.d"
    state: directory          
  
- name: configure burp logrotate
  template:
    src: burp_logrotate.j2
    dest: "{{ etc_dir }}/logrotate.d/burp"

- name: Enable crond service
  service:
    name: "{{ cron_service }}"
    state: started
    enabled: yes
