---
# file tasks/manual_delete.yml

- name: remove burp trash
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ burp_trash }}"

- name: remove Cron task to delete files in burp trash
  cron:
    name: delete files in burp trash
    cron_file: manual_delete
    state: absent
  notify: restart cron server

- name: remove burp logrotate
  file:
    state: absent
    path: /etc/logrotate.d/burp
