---
# file tasks/manual_delete.yml

- name: create burp folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ burp_trash }}"
    - "{{ burp_logs }}"
    - /etc/cron.d

- name: Cron task to delete files in burp trash
  cron:
    name: delete files in burp trash
    job: 'rm -rfv {{ burp_trash  }}/* >> {{ burp_logs }}/manual_delete.log'
    user: root
    cron_file: manual_delete
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.dow }}"
    state: present
  with_items: "{{ burp_cron_delete }}"
  notify: restart cron server

- name: configure burp logrotate
  template:
    src: burp_logrotate.j2
    dest: /etc/logrotate.d/burp

- name: ensure cron is enabled
  service:
    name: cron
    enabled: yes
