
- name: Install supervisor
  package: 
    name: supervisor
    state: latest

- name: configure supervisor logrotate
  template:
    src: supervisor_logrotate.j2
    dest: /etc/logrotate.d/supervisor

- name: configure supervisor service for burp-server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burp-server.conf_supervisor.j2", dest: "/etc/supervisor/conf.d/burp-server.conf" }
  notify: 
    - restart burp server

# only run if burp_module_restore: true
- name: configure supervisor services for burp-restore
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "burp-restore.conf_supervisor.j2", dest: "/etc/supervisor/conf.d/burp-restore.conf" }
  notify: 
    - restart burp restore
  when: burp_module_restore

# only run if burp_module_agent: true
- name: configure supervisor services for buiagent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "buiagent.conf_supervisor.j2", dest: "/etc/supervisor/conf.d/buiagent.conf" }
  notify: 
    - restart buiagent
  when: burp_module_agent
    
- name: ensure supervisor is running
  service:
    name: supervisor
    state: started

- name: ensure supervisor is enabled
  service:
    name: supervisor
    enabled: yes

# - name: disable SysV burp-server service
#   service:
#     name: burp-server
#     state: stopped
#     enabled: no

# Supervisor must be restarted first
- name: Read supervisor config burp-server
  supervisorctl:
    name: burp-server
    state: present

# Only run if burp_module_restore: true
- name: Read supervisor config burp_restore
  supervisorctl:
    name: burp-restore
    state: present
  when: burp_module_restore

# Only run if burp_module_agent: true
- name: Read supervisor config buiagent
  supervisorctl:
    name: buiagent
    state: present
  when: burp_module_agent
  
- name: ensure handlers runs before continue
  meta: flush_handlers
  
 