---

- name: systemd | configure systemd service for burp-server
  template:
    src: "systemd/burp-server.j2"
    dest: "/etc/systemd/system/burp-server.service"
  when: burp_sv_type == 'systemd'

- name: systemd | configure systemd service for burp-server
  template:
    src: "systemd/burp-server_unpriv.j2"
    dest: "/etc/systemd/system/burp-server.service"
  when: burp_sv_type == 'systemd_unprivileged'

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: systemd | enable burp-server service
  systemd:
    daemon-reload: yes
    name: burp-server
    state: started
    enabled: yes

- name: flush handlers
  meta: flush_handlers
