---
# file: handlers/main.yml

- name: restart supervisor
  service:
    name: "{{ supervisor_service }}"
    state: restarted
    sleep: 10

- name: restart burp server
  supervisorctl:
    name: burp-server
    state: restarted
  when: burp_sv_type == 'supervisor'

- name: restart burp server systemd
  supervisorctl:
    name: burp-server
    state: restarted
  when: burp_sv_type == 'systemd' or burp_sv_type == 'systemd_unprivileged'

- name: restart cron server
  service:
    name: "{{ cron_service }}"
    state: restarted

- name: update cache
  apt:
    update_cache: yes
