---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:

  - name: ansible_test-04
    image: molecule_local/fedora-rawhide2
    command: /sbin/init
    capabilities:
      - SYS_ADMIN    
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: True

  - name: ansible_test-01
    image: solita/ubuntu-systemd:16.04
    privileged: True
    command: /sbin/init
    capabilities:
      - SYS_ADMIN    
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"        
    groups:
      - group1
  # In docker cannot be tested with centos 7 due to https://github.com/ansible/ansible-modules-core/issues/593
  
  - name: ansible_test-03
    image: centos/systemd
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: True
    groups:
      - group1

provisioner:
  name: ansible
  inventory:
    group_vars:
      master:
        burpsrcext: "zip"
        burp_version: "master"
        burp_remove_clients:
          - name: client_to_remove
          - name: other_client_to_remove
        burp_server_port_per_operation_bool: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
