---
name: Molecule release
on: 
  push:
    branches:
      - "master"
    # Sequence of patterns matched against refs/tags
    tags:        
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Better to use one scenario per OS for faster performance and easier debugging
        scenario:
          - centos-8
          - ubuntu-2004
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint ansible-lint ansible "molecule[lint,docker]"
      
      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker
      
      - name: check molecule version
        run: molecule --version

      - name: Run molecule converge
        run: "molecule converge --scenario-name ${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: "${{ github.repository }}"

      - name: Run molecule syntax
        run: "molecule syntax --scenario-name ${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: "${{ github.repository }}"

      - name: Run molecule idempotence
        run: "molecule idempotence --scenario-name ${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: "${{ github.repository }}"


# https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# Don't forget to add the secret galaxy_api_key in your repository
  release:
    runs-on: ubuntu-latest
    needs:
      - molecule
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}        
